version: '2'
networks:
  proxy: 
    external: true
  snake: null
services:
  snake:
    build: .
    labels:
      - traefik.backend=snake
      - "traefik.frontend.redirect.regex=^(.*)/snake$$"
      - "traefik.frontend.redirect.replacement=$$1/snake/"
      - "traefik.frontend.rule=Host:annabaier.de; PathPrefix:/snake; ReplacePathRegex:^/snake/(.*) /$$1"
      - traefik.port=80
    networks:
      - proxy
      - snake
  db:
    image: postgres
    hostname: ${postgresHostname}
    environment:
      POSTGRES_PASSWORD: ${postgresPassword}
      POSTGRES_USER: ${postgresUser}
      POSTGRES_DB: ${postgresDB}
    volumes: 
      - "./pgdata:/var/lib/postgresql/data"
    networks:
      - snake
